// Generated by gencpp from file torque_controller/k_cmd.msg
// DO NOT EDIT!


#ifndef TORQUE_CONTROLLER_MESSAGE_K_CMD_H
#define TORQUE_CONTROLLER_MESSAGE_K_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace torque_controller
{
template <class ContainerAllocator>
struct k_cmd_
{
  typedef k_cmd_<ContainerAllocator> Type;

  k_cmd_()
    : k_array()  {
    }
  k_cmd_(const ContainerAllocator& _alloc)
    : k_array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _k_array_type;
  _k_array_type k_array;





  typedef boost::shared_ptr< ::torque_controller::k_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torque_controller::k_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct k_cmd_

typedef ::torque_controller::k_cmd_<std::allocator<void> > k_cmd;

typedef boost::shared_ptr< ::torque_controller::k_cmd > k_cmdPtr;
typedef boost::shared_ptr< ::torque_controller::k_cmd const> k_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torque_controller::k_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torque_controller::k_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torque_controller::k_cmd_<ContainerAllocator1> & lhs, const ::torque_controller::k_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.k_array == rhs.k_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torque_controller::k_cmd_<ContainerAllocator1> & lhs, const ::torque_controller::k_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torque_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torque_controller::k_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torque_controller::k_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torque_controller::k_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torque_controller::k_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torque_controller::k_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torque_controller::k_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torque_controller::k_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97bad9b23c1159dce0e721054b5477af";
  }

  static const char* value(const ::torque_controller::k_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97bad9b23c1159dcULL;
  static const uint64_t static_value2 = 0xe0e721054b5477afULL;
};

template<class ContainerAllocator>
struct DataType< ::torque_controller::k_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torque_controller/k_cmd";
  }

  static const char* value(const ::torque_controller::k_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torque_controller::k_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] k_array\n"
;
  }

  static const char* value(const ::torque_controller::k_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torque_controller::k_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.k_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct k_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torque_controller::k_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torque_controller::k_cmd_<ContainerAllocator>& v)
  {
    s << indent << "k_array[]" << std::endl;
    for (size_t i = 0; i < v.k_array.size(); ++i)
    {
      s << indent << "  k_array[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.k_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TORQUE_CONTROLLER_MESSAGE_K_CMD_H
