// Generated by gencpp from file torque_controller/q_cmd.msg
// DO NOT EDIT!


#ifndef TORQUE_CONTROLLER_MESSAGE_Q_CMD_H
#define TORQUE_CONTROLLER_MESSAGE_Q_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace torque_controller
{
template <class ContainerAllocator>
struct q_cmd_
{
  typedef q_cmd_<ContainerAllocator> Type;

  q_cmd_()
    : q_array()  {
    }
  q_cmd_(const ContainerAllocator& _alloc)
    : q_array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_array_type;
  _q_array_type q_array;





  typedef boost::shared_ptr< ::torque_controller::q_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::torque_controller::q_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct q_cmd_

typedef ::torque_controller::q_cmd_<std::allocator<void> > q_cmd;

typedef boost::shared_ptr< ::torque_controller::q_cmd > q_cmdPtr;
typedef boost::shared_ptr< ::torque_controller::q_cmd const> q_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::torque_controller::q_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::torque_controller::q_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::torque_controller::q_cmd_<ContainerAllocator1> & lhs, const ::torque_controller::q_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.q_array == rhs.q_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::torque_controller::q_cmd_<ContainerAllocator1> & lhs, const ::torque_controller::q_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace torque_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::torque_controller::q_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::torque_controller::q_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torque_controller::q_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::torque_controller::q_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torque_controller::q_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::torque_controller::q_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::torque_controller::q_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc698571bcbd99704d5af623bbfb7675";
  }

  static const char* value(const ::torque_controller::q_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc698571bcbd9970ULL;
  static const uint64_t static_value2 = 0x4d5af623bbfb7675ULL;
};

template<class ContainerAllocator>
struct DataType< ::torque_controller::q_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "torque_controller/q_cmd";
  }

  static const char* value(const ::torque_controller::q_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::torque_controller::q_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] q_array\n"
;
  }

  static const char* value(const ::torque_controller::q_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::torque_controller::q_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct q_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::torque_controller::q_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::torque_controller::q_cmd_<ContainerAllocator>& v)
  {
    s << indent << "q_array[]" << std::endl;
    for (size_t i = 0; i < v.q_array.size(); ++i)
    {
      s << indent << "  q_array[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TORQUE_CONTROLLER_MESSAGE_Q_CMD_H
